# Generated by Django 2.1.2 on 2018-10-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20181003_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='remaining_budget',
            field=models.CharField(default='0.0', max_length=180),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.CharField(default='0.0', max_length=180),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(default='0.0', max_length=180),
        ),
    ]
